global:
  # Registry where cnc-nfdata-collector image present.
  image:
    repository: cne-bastion-1:5000

  #Host machine is the slave node on which this job is scheduled. Make sure path is present on node already.
  outputPath: /tmp/dataexport-test

  # Name of the slave where fetched data can be kept.
  slaveNodeName: cne-k8s-node-1

  #Storage to be allocated to persistence
  capacityStorage: 5Gi
  
  #Mount slave path with pod
  storagePod: false

  #Mention the URL of elasticSearch here.#Mention the URL of elasticSearch here.
  elasticSearchURL: "http://10.233.14.43:9200"

  #Mention the URL of prometheus here.
  prometheusURL: "http://10.75.151.168"
  
  #Time range for which data should fetched
  interval: "24" # IN HOURS

  #In case, data other than last few hours from now is required.
  pastTimeSpot: "2020-10-06T00:00:00Z"

LogsExporter:

  # Enable to fetch logs Data
  enabled: true

  # provide the list of json key values which must exist in the logs to be fetched
  inclusionFilters: |
    - kubernetes.namespace_name=ocnrf

  # provide the list of json key values which must not exist in the logs to be fetched
  #exclusionFilters: |
  # - audit_logs=true

  #Default REGEX value for this param is '^.*$' which means select all the indices.
  match: '^.*$'

MetricsExporter:

  # Enable to fetch Metrics Data
  enabled: true

  # provide the list of labels which must exist in the metrics to be fetched
  inclusionFilters: |
    - namespace=ocnrf

  # Timestamp difference between two data points in seconds
  step: "30"

TracesExporter:

  # Enable to fetch Traces Data
  enabled: true

  # provide the list of tags which must exist in the traces to be fetched
  inclusionFilters: |
    - namespace=ocnrf

  # provide the list of labels which must not exist in the traces to be fetched
#  exclusionFilters: |
#    - exclude_field=true

  #Default REGEX value for this param is '^.*$' which means select all the indices.
  match: '^jaeger.*$'
